services:
  attacker_prometheus:
    image: quay.io/prometheus/prometheus
    container_name: attacker_prometheus
    volumes:
      - ./database/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  attacker_node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: attacker_node-exporter
    restart: always
