[workspace]
authors = ["motty <motty.mio2@gmail.com>"]
channels = ["conda-forge"]
name = "roboapp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pnpm = ">=10,<11"
nodejs = ">=22,<23"
uv = ">=0.9.3,<0.10"
rust = ">=1.90.0,<1.91"
