global:
  scrape_interval: 15s
  external_labels:
    monitor: "attacker-monitor"
scrape_configs:
  - job_name: "node-exporter"
    scrape_interval: 1s
    static_configs:
      - targets:
          - "attacker_node-exporter:9100"
  # - job_name: 'attacker-apps'
  #   scrape_interval: 1s
  #   static_configs:
  #     - targets:
  #       # main_camera_system
  #       - "host.docker.internal:9901"
